### ISSUE TITLE
Compilation Error for Flora

### ISSUE THREAD

**Issue by nemessisc** [shirriff/Arduino-TV-B-Gone#2]
Working on a solution but still I get this error: 

error: variable 'NApowerCodes' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 const struct IrCode *NApowerCodes[] PROGMEM = {

**Comment by ElectricRCAircraftGuy** [comment]
I have just merged a version 1.3 of the code, with improvements, including this PROGMEM fix. Should compile fine for everyone now. Please try it.
